### ISSUE TITLE
Move colab notebook "IATI Publisher Data Getter #master" into this repo

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/iati-notebooks#1]
This is on colab - https://colab.research.google.com/drive/1UihxpcixZGbHOYf5EDyMY_uX1zQR33Yu#scrollTo=y4RJqtbd8E7k

We need to work out the best workflow for this - its possible we could save from Colab directly, or download it and commit it manually.

**Comment by stevieflow** [comment]
I guess a related issue might then be: how we apply changes in master to any copies of master?  

I dont think that would be possible - but would be good to know

**Comment by Bjwebb** [comment]
It looks like we can do a mass copy/paste of cells, which means we don't need a new notebook URL each time.

Do you also want to make changes to copies, and preserve those? Or is it okay to replace the whole thing and just reset the publisher registry ID?

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IATI Colab notebook 3.0](https://trello.com/c/U8VZB4km/12-iati-colab-notebook-30)
