### ISSUE TITLE
Run colab notebook against files that aren't on the registry

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/iati-notebooks#3]
Often we want to test data that is not published / manually configured

Options for this are file upload, or use a file from google docs.

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IATI Colab notebook 3.0](https://trello.com/c/U8VZB4km/12-iati-colab-notebook-30)

**Comment by stevieflow** [comment]
This is great - tested fine

Just change the name of the example input file to upload.xml @Bjwebb
