### ISSUE TITLE
Check that we are selecting "current" activities correctly, in colab notebook

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/iati-notebooks#4]
This should be the definition in line with the Aid Transparency Index: https://github.com/pwyf/latest-index-indicator-definitions/issues/1

**Comment by stevieflow** [comment]
@Bjwebb there's also the definition of "current" in terms of the IATI dashboard http://publishingstats.iatistandard.org/comprehensiveness.html#h_pseudocode

```
end dates =
    For each activity-date of type end-planned or end-actual
        Parse activity-date/@iso-date as an iso date ('yyyy-mm-dd...')
        If this does not work parse activity-date/text() as an iso date ('yyyy-mm-dd...')
        If neither work, ignore this activity-date

If activity-status/@code exists
    If activity-status/@code is 2 exists
        The activity is current
    Else
        The activity is current
Else
    If end dates (see above) is empty
        The activity is current
    Else
        If there is an end date where (date year >= current year)
            The activity is current
        Else
            The activity is not current
```
Within the notebook it'd be good to account for the two definitions, to see what impact they have on any corpus.

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IATI Colab notebook 3.0](https://trello.com/c/U8VZB4km/12-iati-colab-notebook-30)

**Comment by Bjwebb** [comment]
I've created a new notebook to test our "current" selection: https://colab.research.google.com/drive/1KV-frydA-5qjbVCPuagfp_DO_F7gc4GW

This uses sample activities that we expect to be current or not. These are taken from PWYFs test of their own function, so should be a good test. Our code behaves as expected.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

Do you need me to test in any way?

**Comment by Bjwebb** [comment]
No, only once I add the IATI dashboard definition to the main notebook.
