### ISSUE TITLE
CoVE validation - ensure that this runs on the current dataset rather than the whole corpus

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/iati-notebooks#7]
I've changed this manually @Bjwebb , but one to add to master...

**Comment by Bjwebb** [comment]
Is this just a matter of changing `combined.xml` to `combined_current.xml`? In:

```python
r = rq.post(url, files=files, data={"name": "combined.xml"})
```

**Comment by stevieflow** [comment]
Yep exactly - have tested the change with manual cove and this works.  Just a case of making this so in Master

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IATI Colab notebook 3.0](https://trello.com/c/U8VZB4km/12-iati-colab-notebook-30)

**Comment by stevieflow** [comment]
This works - thanks @Bjwebb
